wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:linguage>", views.pages, name="pages" ),
    path("search/", views.search, name="search"),
    path("newpage/", views.newpage, name="newpage"),
    path("edit<str:entry>/", views.edit, name="edit"),
    path("random/", views.ran, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
import markdown2
from . import util
from django import forms
from django.contrib import messages
import random

class NewEntryForm(forms.Form):
    tittle = forms.CharField(label="Tittle")
    textarea = forms.CharField(label="Content (Markdown)", widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def pages(request, linguage):
    content = util.get_entry(linguage)
    converted = markdown2.markdown(content)
    
    return render(request, "encyclopedia/content.html", {
        "page": converted,
        "entry": linguage
    })

def search(request):
    for i in util.list_entries():
        if request.method == "POST" and request.POST["searched"] == i:
            searched = request.POST["searched"]
            return HttpResponseRedirect(f"/wiki/{searched}")
    return render(request, "encyclopedia/search.html", {
        "searched": request.POST["searched"],
        "entry":util.list_entries
    })

def newpage(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            valid_tittle = form.cleaned_data["tittle"]
            valid_textarea = form.cleaned_data["textarea"]
            allentries = list(map(lambda x : x.casefold(), util.list_entries()))
            if valid_tittle.casefold() not in allentries:
                util.list_entries().append(util.save_entry(valid_tittle, valid_textarea))
                return HttpResponseRedirect(f"/wiki/{valid_tittle}")
            else: messages.error(request, "This tittle already exists") 
            return redirect("/wiki/newpage/")
    return render(request, "encyclopedia/newpage.html", {
        "forms": NewEntryForm()
    })

def edit(request, entry):
    class NewEditForm(forms.Form):
        editedtittle = forms.CharField(label="Tittle", initial=entry, disabled=True)
        editedtextarea = forms.CharField(label="Content (Markdown)", widget=forms.Textarea, initial=util.get_entry(entry))
    if request.method == "POST":
        form = NewEditForm(request.POST)
        if form.is_valid():
            valid_editedtittle = form.cleaned_data["editedtittle"]
            valid_editedtextarea = form.cleaned_data["editedtextarea"]
            util.save_entry(valid_editedtittle, valid_editedtextarea)
            return HttpResponseRedirect(f"/wiki/{entry}")
    return render(request, "encyclopedia/edit.html", {
        "lin": entry,
        "content": util.get_entry(entry),
        "form": NewEditForm()
    })

def ran(request):
    routelist = util.list_entries()
    randomroute = random.choice(routelist)
    return HttpResponseRedirect(f"/wiki/{randomroute}")

wiki/encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}
{% block content %}
<div class="container">
    {%csrf_token%}
    {{page|safe}}
    <a href="{% url 'wiki:edit' entry %}" class="btn btn-success">Edit this page</a>
</div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{%block edit %}
<div>
    <form action="" method="POST">
        {%csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-success"> Save Changes </button>
    </form>
</div>

<style>
    form {
        display: grid;
        place-items: center;
        gap: 10px;
    }
    label {
        display: grid;
        margin-bottom: 15px;
        width: 100%;
    }

    div {
        text-align: center;
        width: 100%;
    }

    #input, textarea {
        width: 100%;
    }
</style>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:pages' entry%}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method=POST>
                    {% csrf_token %}
                    <input class="search" type="text" placeholder="Search Encyclopedia" name="searched">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{%url 'wiki:newpage' %}"> Create New Page</a> 
                </div>
                <div>
                   <a href="{%url 'wiki:random' %}" >Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">

                {% block body %}
                {% endblock %}

                {% block content %}
                {% endblock %}

                {% block search %}
                {% endblock %}

                {%block newpage %}
                {%endblock%}

                {%block edit%}
                {%endblock%}
                
            </div>
            <div>
                
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{%block newpage %}
<div id="tittle">
    <h1>Create a new page in Markdown Linguage</h1>
</div>
<br>
<div class="container">
    <div class="mb-3">
        {%if messages%}
            {%for msg in messages%}
        <div class="alert alert-danger" role="alert">
            {{msg}}
        </div>
            {%endfor%}
        {% else %}
        <form action="" method="POST">
            {% csrf_token %}
            {{forms}}
            <button type="submit" class="btn btn-primary">Create new page </button>
        </form>
        {%endif%}
        
    </div>
</div>

<style> 
    #tittle {
        text-align: center;
    }

    .container {
        text-align: center;
    }
    #id_tittle {
        width: 100%;
    }
    #id_textarea {
        width: 100%;
        height: 50%;
    }
    button {
        margin-top: 10px;
    }
</style>

{%endblock%}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block search %}

<ul>
    <h1>Your search result is:</h1>
    {% for teste in entry %}
        {% if searched in teste %}
            <li><a href="{% url 'wiki:pages' teste %}"> {{teste}}</a></li>
        {% endif %}
    {%endfor%}
</ul>
{% endblock%}